apiVersion: v2
name: netbox
description: A Helm chart for deploying NetBox with Redis
type: application
version: 1.1.0
appVersion: "3.6.2"

dependencies:
  - name: redis
    version: "17.3.11"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled