apiVersion: v2
name: netbox
version: 1.0.0
description: Helm chart for deploying NetBox in a Kubernetes cluster
appVersion: "3.6.2"
type: application

dependencies:
  - name: redis
    version: "17.3.11"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
