apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbox
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: netbox
  template:
    metadata:
      labels:
        app: netbox
    spec:
      containers:
        - name: netbox
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DB_HOST
              value: "{{ .Values.postgresql.auth.database }}"
            - name: REDIS_HOST
              value: "redis-master"
            - name: PLUGINS
              value: "{{ join ',' .Values.config.plugins.list }}"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: netbox-data
              mountPath: /opt/netbox/netbox/media
      volumes:
        - name: netbox-data
          persistentVolumeClaim:
            claimName: netbox-pvc