apiVersion: v1
kind: Secret
metadata:
  name: netbox-secret
type: Opaque
data:
  db_password: {{ if .Values.postgresql.external.enabled }}{{ .Values.postgresql.external.password | b64enc | quote }}{{ else }}{{ .Values.postgresql.password | b64enc | quote }}{{ end }}